Bug fixes

diff --git a/eb-delbranch b/eb-delbranch
--- a/eb-delbranch
+++ b/eb-delbranch
@@ -19,7 +19,7 @@ for branch in "$@"
 do
 	if [[ "${branch}" == "develop" || "${branch}" == "master" ]]
 	then
-		echo "Deletion of \"${branch}\" branch is verboten. Skipping."
+		echo "Deletion of the \"${branch}\" branch is verboten. Skipping."
 		exitcode=1
 		continue
 	fi
@@ -27,26 +27,24 @@ do
 	git checkout "${branch}"
 	if [[ $? -ne 0 ]]
 	then
-		echo "Unable to switch to \"${branch}\" branch. Skipping."
+		echo "Unable to switch to the \"${branch}\" branch. Skipping."
 		exitcode=1
 		continue
-	else
-		echo "Switched to \"${branch}\" branch"
 	fi
 
 	merge_output=$(git merge develop)
-	if [[ $? -ne 0 || merge_output != "Already up-to-date." ]]
+	if [[ $? -ne 0 || "${merge_output}" != "Already up-to-date." ]]
 	then
 		echo "\"${branch}\" is not up-to-date with develop."
 		echo "It is therefore unsuitable for automatic deletion and will be skipped."
 		exitcode=1
 		continue
 	else
-		echo "Verified that \"${branch}\" branch is in sync with local develop branch"
+		echo "Verified that the \"${branch}\" branch is in sync with local develop branch"
 	fi
 
 	pull_output=$(git pull)
-	if [[ $? -ne 0 || pull_output != "Already up-to-date." ]]
+	if [[ $? -ne 0 || "${pull_output}" != "Already up-to-date." ]]
 	then
 		echo "\"${branch}\" is different from its remote."
 		echo "It is therefore unsuitable for automatic deletion and will be skipped."
@@ -58,14 +56,14 @@ do
 	# want to aggregate STDERR and STDOUT; we want to throw away STDOUT and
 	# print STDERR to STDOUT in its stead.	
 	push_output=$(git push -u bprgithub FreeXL 2>&1 1>/dev/null)
-	if [[ $? -ne 0 || push_output != "Everything up-to-date" ]]
+	if [[ $? -ne 0 || "${push_output}" != "Everything up-to-date" ]]
 	then
 		echo "\"${branch}\" is different from its remote."
 		echo "It is therefore unsuitable for automatic deletion and will be skipped."
 		exitcode=1
 		continue
 	else
-		echo "Verified that \"${branch}\" branch is in sync with its remote"
+		echo "Verified that the \"${branch}\" branch is in sync with its remote"
 	fi
 
 	git checkout develop || errexit "an unexpected error occurred while switching to the develop branch"
@@ -73,21 +71,21 @@ do
 	git push bprgithub ":${branch}"
 	if [[ $? -ne 0 ]]
 	then
-		echo "Unable to delete remote for \"${branch}\" branch. Skipping."
+		echo "Unable to delete the remote for the \"${branch}\" branch. Skipping."
 		exitcode=1
 		continue
 	else
-		echo "Deleted remote for \"${branch}\" branch"
+		echo "Deleted the remote for the \"${branch}\" branch"
 	fi
 
 	git branch -d "${branch}"
 	if [[ $? -ne 0 ]]
 	then
-		echo "Unable to delete \"${branch}\" branch. Skipping."
+		echo "Unable to delete the \"${branch}\" branch. Skipping."
 		exitcode=1
 		continue
 	else
-		echo "Deleted \"${branch}\" branch"
+		echo "Deleted the \"${branch}\" branch"
 	fi
 done
 
